import React,{useState} from 'react';
import {Shield,Video,AlertTriangle,Users,Car,FileClock,Settings,Sun,Moon,LogOut,Wifi,Activity,Menu,X,CheckCircle,ChevronRight} from 'lucide-react';
import {cameras,alerts,persons,vehicles,events} from './data/mockData';

const nav=[['live','Live Surveillance',Video],['alerts','Alerts',AlertTriangle],['human','Human Tracking',Users],['vehicle','Vehicle Intelligence',Car],['events','Event Logs',FileClock],['system','System',Settings]];
function Header({theme,setTheme,onLogout}){return <header><div className="header-brand"><Shield size={25}/><div><b>BORDER SENTINEL</b><small>AI SURVEILLANCE COMMAND CENTER</small></div></div><div className="system-pill"><span className="online-dot"/> SYSTEM ONLINE</div><div className="header-right"><span className="date">19 Sep 2026</span><span className="clock">10:08:31 AM</span><span className="mini"><Video size={15}/> Cameras <b>12/12</b></span><span className="mini"><Wifi size={15}/> Network <b>Good</b></span><button className="theme-btn" onClick={()=>setTheme(theme==='dark'?'light':'dark')}>{theme==='dark'?<Sun size={17}/>:<Moon size={17}/>}</button><button className="admin" onClick={onLogout}><LogOut size={15}/> Admin</button></div></header>}
function Sidebar({page,setPage,mobileOpen,setMobileOpen}){return <aside className={mobileOpen?'open':''}><div className="mobile-close"><button onClick={()=>setMobileOpen(false)}><X/></button></div>{nav.map(([key,label,Icon])=><button key={key} className={page===key?'active':''} onClick={()=>{setPage(key);setMobileOpen(false)}}><Icon size={18}/><span>{label}</span>{key==='alerts'&&<em>3</em>}</button>)}</aside>}
function Layout({children,page,setPage,theme,setTheme,onLogout}){const [mobile,setMobile]=useState(false);return <div className="app"><Header theme={theme} setTheme={setTheme} onLogout={onLogout}/><button className="mobile-menu" onClick={()=>setMobile(true)}><Menu/></button><div className="body"><Sidebar page={page} setPage={setPage} mobileOpen={mobile} setMobileOpen={setMobile}/><main>{children}</main></div></div>}
const Badge=({children,type='medium'})=><span className={`badge ${type.toLowerCase()}`}>{children}</span>;
function Live(){return <><PageTitle title="Live Surveillance" sub="Real-time CCTV feeds with AI detection"/><div className="toolbar"><span>All Cameras</span><span className="select">12 Cameras ▾</span></div><div className="camera-grid">{cameras.map(c=><div className="camera-card" key={c.id}><div className="cam-head"><b>{c.id}</b><span>● LIVE</span></div><div className="video-placeholder"><div className={`detect ${c.kind==='Person'?'person':'vehicle'}`}>{c.kind} {c.confidence}%</div><div className="scanline"/><div className="fake-scene">CCTV FEED</div></div><div className="cam-foot"><span>{c.kind} Detected</span><time>{c.time}</time></div></div>)}</div></>}
function Alerts(){return <><PageTitle title="Alerts & Notifications" sub="Real-time threat alerts with threat classification"/><div className="filters"><span className="active-filter">All</span><span>Critical</span><span>High</span><span>Medium</span><span>Info</span><button className="outline-btn">Mark All Read</button></div><div className="alert-layout"><div className="alert-list">{alerts.map(a=><div className="alert-row" key={a.id}><div className={`alert-icon ${a.type==='HUMAN INTRUSION'?'red':a.type==='SUSPICIOUS ACTIVITY'?'orange':'blue'}`}><AlertTriangle size={18}/></div><div><b>{a.type}</b><small>{a.camera} • 19 Sep 2026 • {a.time}</small></div><strong>{a.confidence}%</strong><Badge type={a.level}>{a.level}</Badge></div>)}</div><div className="detail-card"><Badge type="critical">CRITICAL</Badge><h2>HUMAN INTRUSION</h2><div className="snapshot"><div className="person-shape"/></div><p>Camera: C-07</p><p>Confidence: <b>94.8%</b></p><p>Time: <b>10:08:31 AM</b></p><div className="actions"><button className="primary-btn">View Live</button><button className="outline-btn">Acknowledge</button></div></div></div></>}
function Human(){return <><PageTitle title="Human Tracking" sub="Detected persons and current movement status"/><div className="stat-grid one"><Stat icon={Users} label="Active Persons" value={persons.length}/></div><div className="table-card"><div className="table-title">Active Persons</div><table><thead><tr><th>Camera</th><th>Status</th></tr></thead><tbody>{persons.map(p=><tr key={p.camera}><td>{p.camera}</td><td><span className={`status ${p.status==='Moving'?'moving':'stationary'}`}>● {p.status}</span></td></tr>)}</tbody></table></div></>}
function Vehicle(){return <><PageTitle title="Vehicle Intelligence" sub="Vehicle classification and number plate recognition"/><div className="stat-grid">{['Vehicles Detected','Cars','Bikes'].map((x,i)=><Stat key={x} icon={Car} label={x} value={[vehicles.length,vehicles.filter(v=>v.type==='Car').length,vehicles.filter(v=>v.type==='Bike').length][i]}/>)}</div><div className="table-card"><div className="table-title">Detected Vehicles</div><table><thead><tr><th>Type</th><th>Number Plate</th><th>Detection Time</th></tr></thead><tbody>{vehicles.map(v=><tr key={v.plate}><td>{v.type}</td><td><b>{v.plate}</b></td><td>{v.time}</td></tr>)}</tbody></table></div></>}
function Events(){return <><PageTitle title="Event Logs" sub="Detection and surveillance event history"/><div className="table-card"><div className="table-title">Recent Events <span>19 September 2026</span></div><table><thead><tr><th>Time</th><th>Event</th><th>Camera</th><th>Severity</th></tr></thead><tbody>{events.map(e=><tr key={e.time+e.event}><td>{e.time}</td><td>{e.event}</td><td>{e.camera}</td><td><Badge type={e.level}>{e.level}</Badge></td></tr>)}</tbody></table></div></>}
function System(){return <><PageTitle title="System" sub="System and infrastructure status"/><div className="system-grid"><StatusCard icon={Activity} title="System Status" value="ONLINE" good/><StatusCard icon={Video} title="Cameras" value="12 / 12" good/><StatusCard icon={Wifi} title="Network" value="GOOD" good/><StatusCard icon={CheckCircle} title="AI Detection" value="ACTIVE" good/></div></>}
function PageTitle({title,sub}){return <div className="page-title"><div><h1>{title}</h1><p>{sub}</p></div><div className="crumb">19 Sep 2026 <ChevronRight size={15}/></div></div>}
function Stat({icon:Icon,label,value}){return <div className="stat"><div className="stat-icon"><Icon size={20}/></div><div><small>{label}</small><b>{value}</b></div></div>}
function StatusCard({icon:Icon,title,value}){return <div className="status-card"><Icon size={24}/><div><small>{title}</small><h2>{value}</h2><span><i/> Operational</span></div></div>}
export default function App({theme,setTheme,onLogout}){const [page,setPage]=useState('live');const content={live:<Live/>,alerts:<Alerts/>,human:<Human/>,vehicle:<Vehicle/>,events:<Events/>,system:<System/>}[page];return <Layout page={page} setPage={setPage} theme={theme} setTheme={setTheme} onLogout={onLogout}>{content}</Layout>}
